// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlihoe5t31XeTxMyItyVNCxCDLyibwzOc',
    appId: '1:58669612630:web:d87dac2f5ec6fdfb3505f7',
    messagingSenderId: '58669612630',
    projectId: 'newflutter-76687',
    authDomain: 'newflutter-76687.firebaseapp.com',
    storageBucket: 'newflutter-76687.appspot.com',
    measurementId: 'G-W2PVSFBDM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQau-NldX7Q0CmqfZoHQ1xPHxCw1SKXs',
    appId: '1:58669612630:android:90cdb0fef2192b6d3505f7',
    messagingSenderId: '58669612630',
    projectId: 'newflutter-76687',
    storageBucket: 'newflutter-76687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtlL8J0Snv9sYELM1l7ixkFq5PW4IQPRk',
    appId: '1:58669612630:ios:07ca6bbe9817f1c73505f7',
    messagingSenderId: '58669612630',
    projectId: 'newflutter-76687',
    storageBucket: 'newflutter-76687.appspot.com',
    iosBundleId: 'com.example.newflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtlL8J0Snv9sYELM1l7ixkFq5PW4IQPRk',
    appId: '1:58669612630:ios:07ca6bbe9817f1c73505f7',
    messagingSenderId: '58669612630',
    projectId: 'newflutter-76687',
    storageBucket: 'newflutter-76687.appspot.com',
    iosBundleId: 'com.example.newflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlihoe5t31XeTxMyItyVNCxCDLyibwzOc',
    appId: '1:58669612630:web:168e0818c9c1674d3505f7',
    messagingSenderId: '58669612630',
    projectId: 'newflutter-76687',
    authDomain: 'newflutter-76687.firebaseapp.com',
    storageBucket: 'newflutter-76687.appspot.com',
    measurementId: 'G-R54YFF71QW',
  );
}
